apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: greet-service
  name: greet-service
  namespace: default
  
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: greet-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
       labels:
        app: greet-service
    spec:
      containers:
      - image: sbtalk71/greet-service:1.0
        imagePullPolicy: IfNotPresent
        name: greet-service
       
      restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: greet-service
  name: greet-service
  namespace: default
  
spec:
  
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: greet-service
  sessionAffinity: None
  type: LoadBalancer